### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by chaolv123** [AbdoulMa/30DayMapChallenge#1]
Dear 
I use you code has the follow error information :
Error in loadNamespace(x) : doesn't exist ‘albersusa’

**Comment by chaolv123** [comment]
Error in loadNamespace(x) : 不存在叫‘albersusa’这个名字的程辑包

**Comment by AbdoulMa** [comment]
Hi 

Be sure you have `albersusa` installed. The package is not available on CRAN so you have to install it with the `remotes` package. 

```
remotes::install_github("hrbrmstr/albersusa")
```
![Here](https://github.com/hrbrmstr/albersusa) is its official repository. 
Feel free to let me know if the code compile well or if you have any other issue.
